
// slowly marking this off as I go through the data
const foodCategories = [
  'Cooked Grains',
  '100% Juice',
  'Rice',
  'Citrus juice',
  'Milk, reduced fat',
  'Pasta, noodles, cooked grains',
  'Fruit juice',
  'Milk and Dairy Beverages, Nonalcoholic',
  'Milk',
  'Milk, whole',
  'Milk, lowfat',
  'Milk, nonfat',

  'Yeast breads',
  'Vegetable juice',
  'Rolls and buns',
  'Diet Beverages',
  'Flavored milk, whole',
  'Bagels and English muffins',
  'Diet soft drinks',
  'Flavored milk, reduced fat',
  'Tortillas',
  'Diet sport and energy drinks',
  'Flavored milk, lowfat',
  'Quick Breads and Bread Products',
  'Other diet drinks',
  'Flavored milk, nonfat',
  'Biscuits, muffins, quick breads',
  'Sweetened Beverages',
  'Soft drinks',
  'Fruit drinks',
  'Milk substitutes',
  'Nutritional beverages',
  'Oatmeal',
  'Coffee and Tea',
  'Yogurt',
  'Grits and other cooked cereals',
  'Coffee',
  'Yogurt, regular',
  'SNACKS AND SWEETS',
  'Tea',
  'Yogurt, Greek',
  'ALCOHOLIC BEVERAGES',
  'PROTEIN FOODS',
  'Potato chips',
  'Alcoholic Beverages',
  'Meats',
  'Tortilla, corn, other chips',
  'Beef, excludes ground',
  'Popcorn',

  'Pretzels/snack mix',
  'Crackers',
  'WATER',
  'Liver and organ meats',
  'Saltine crackers',


  'Bottled water',
  'Chicken, whole pieces',
  'Cereal bars',
  'Flavored or Enhanced Water',
  'Chicken patties, nuggets and tenders',

  'FATS AND OILS',
  'Fats and Oils',
  'Doughnuts, sweet rolls, pastries',
  'Butter and animal fats',
  'Eggs',
  'Candy',
  'Margarine',
  'Eggs and omelets',
  'Candy containing chocolate',
  'Cream cheese, sour and whipped cream',
  'Cured Meats/Poultry',
  'Candy not containing chocolate',
  'Cream and cream substitutes',
  'Cold cuts and cured meats',
  'Other Desserts',
  'Mayonnaise',
  'Bacon',
  'Ice cream and frozen dairy desserts',
  'Salad dressings and vegetable oils',
  'Frankfurters',
  'Pudding',
  'CONDIMENTS AND SAUCES',
  'Sausages',
  'Gelatins, ices, sorbets',
  'Condiments and Sauces',
  'Plant-based Protein Foods',
  'FRUIT',
  'Tomato-based condiments',
  'Beans, peas, legumes',
  'Fruits',
  'Soy-based condiments',
  'Nuts and seeds',
  'Apples',
  'Mustard and other condiments',
  'Processed soy products',
  'Bananas',
  'Olives, pickles, pickled vegetables',
  'MIXED DISHES',
  'Grapes',
  'Pasta sauces, tomato-based',
  'Mixed Dishes - Meat, Poultry, Seafood',
  'Peaches and nectarines',
  'Dips, gravies, other sauces',
  'Meat mixed dishes',
  'Berries',
  'SUGARS',
  'Poultry mixed dishes',
  'Citrus fruits',
  'Sugars',
  'Seafood mixed dishes',
  'Melons',
  'Sugars and honey',
  'Mixed Dishes - Grain-based',
  'Dried fruits',
  'Sugar substitutes',
  'Rice mixed dishes',
  'Other fruits and fruit salads',
  'Jams, syrups, toppings',
  'Pasta dishes, excludes macaroni and cheese',
  'VEGETABLES',
  'INFANT FORMULA & BABY FOOD',
  'Macaroni and cheese',
  'Vegetables',
  'Baby Foods',
  'Turnovers and other grain-based items',
  'Tomatoes',
  'Baby food: cereals',
  'Mixed Dishes - Asian',
  'Carrots',
  'Baby food: fruit',
  'Fried rice and lo/chow mein',
  'Other red and orange vegetables',
  'Baby food: vegetable',
  'Stir-fry and soy-based sauce mixtures',
  'Dark green vegetables, excludes lettuce',
  'Baby food: meat and dinners',
  'Egg rolls, dumplings, sushi',
  'Lettuce and lettuce salads',
  'Baby food: yogurt',
  'Mixed Dishes - Mexican',
  'String beans',
  'Baby food: snacks and sweets',
  'Burritos and tacos',
  'Onions',
  'Baby Beverages',
  'Nachos',
  'Corn',
  'Baby juice',
  'Other Mexican mixed dishes',
  'Other starchy vegetables',
  'Baby water',
  'Mixed Dishes - Pizza',
  'Other vegetables and combinations',
  'Infant Formulas',
  'Pizza',
  'Vegetable mixed dishes',
  'Formula, ready-to-feed',
  'Mixed Dishes - Sandwiches (single code)',
  'White Potatoes',
  'Formula, prepared from powder',
  'Burgers',
  'White potatoes, baked or boiled',
  'Formula, prepared from concentrate',
  'Chicken/turkey sandwiches',
  'French fries and other fried white potatoes',
  'Human Milk',
  'Egg/breakfast sandwiches',
  'Mashed potatoes and white potato mixtures',
  'Human milk',
  'Frankfurter sandwiches',
  'OTHER',
  'Other sandwiches',
  'Protein and nutritional powders',
  'Mixed Dishes - Soups',
  'Not included in a food category',
]
